# fly.toml app configuration file generated for peter-kuhmann-projects-qwik-multi-tenancy on 2023-06-03T15:43:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "peter-kuhmann-projects-qwik-multi-tenancy"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
